### ISSUE TITLE
Configuration file support

### ISSUE THREAD

**Issue by dtcyganok** [xvzc/SpoofDPI#241]
### Description

It would be nice to have ability to control the SpoofDPI behavior (all of the cli options) via config file.

**Comment by gray1717** [comment]
+ it would also be nice to be able to run the application in daemon mode

**Comment by Ledorub** [comment]
We can create a config file of the following format:
```yaml
proxy:
    addr: "127.0.0.1"
    port: 8080
    connection:
        timeout: 1
        https:
            window-size: 0
    system-proxy: false
    patterns:
        - "example.com"
dns:
    addr: "8.8.8.8"
    port: 53
    enable-doh: false
    ip-v4-only: false
output:
    silent: false
    debug: false
```
and specify the path to it via `-config-file` option.

| Source   | Precedence |
| -------- | :----------: |
| Defaults | 0                  |
| File         | 1                  |
| Flags      | 2                 |

@xvzc
